### ISSUE TITLE
Folder Service

### ISSUE THREAD

**Issue by heroes-coding** [cooksystemsinc/final-project-orange#13]
Implement the folder service.

**Comment by forestwhill** [comment]
Updated estimate to 5, on account of the added complexity of a folder's file structure.

**Comment by forestwhill** [comment]
All endpoints have been implemented, but upload and download cannot be properly tested without interaction with the client. As such, we will test from the develop branch, adjust from there, and then close this issue.

**Comment by forestwhill** [comment]
Download endpoint was not completed before end of sprint. Will be top priority in second sprint.
