### ISSUE TITLE
Library Container

### ISSUE THREAD

**Issue by heroes-coding** [cooksystemsinc/final-project-orange#25]
Create Library Container

### Wireframe
https://projects.invisionapp.com/freehand/document/iLqjesAfc

### Styling Checklist
- [ ] set total cards visible on the page to 8 so the paginator will have an open spot bottom right
- [ ] get paginator into the bottom right corner
- [x] put a bar separating the card title from the rest of the card
- [x] make create folder/upload folder card fit the sidebar upon width change
- [ ] give the create folder/upload folder card the same hover effect as library and trash
- [x] change spacing and alignment of the create folder/upload folder card so they are centered and larger
- [x] alter the corners of create folder/upload folder card to make them match library and trash
- [x] make the upload file card fit the sidebar upon width change
- [ ] put a dividing bar between library/ trash and the other cards in the sidebar
- [ ] fix current directory tag to be top left and reflective of the path
- [x] make sidebar and view connected but divided by a line 
- [x] make the sidebar and view stretch to fit the whole screen
- [ ]
- [ ]

**Comment by JEstes93** [comment]
Spoke with Austin about a strategy for styling

**Comment by JEstes93** [comment]
Only major task to be completed is styling and remaining implementation is flexible.
