### ISSUE TITLE
Trash Container

### ISSUE THREAD

**Issue by heroes-coding** [cooksystemsinc/final-project-orange#28]
Finish Trash Container

### Wireframe
https://projects.invisionapp.com/freehand/document/iLqjesAfc

### Styling Checklist
- [ ] honestly, the changes made to the library folder should fix the majority of the styling issues here
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by JEstes93** [comment]
This currently functions to spec, although its not pretty
