### ISSUE TITLE
Add Folder Modal (Component)

### ISSUE THREAD

**Issue by heroes-coding** [cooksystemsinc/final-project-orange#44]
A popup that has a text input box and a create folder callback

### Wireframe
https://projects.invisionapp.com/freehand/document/iLqjesAfc

### Styling Checklist
- [ ] step 1

**Comment by JEstes93** [comment]
This thing isn't included in the wireframe. Need to discuss with team.

**Comment by JEstes93** [comment]
Implemented this for creating a new folder
