### ISSUE TITLE
Update project with thorough JavaDocs and JSDocs

### ISSUE THREAD

**Issue by JEstes93** [cooksystemsinc/final-project-orange#51]
Propose the team thoroughly document the current codebase with JavaDocs and JSDocs. 

This will assist new team members in familiarizing with the code base, increase the speed and efficiency of on-boarding new developers with the project, and promote a more thorough, comprehensive understanding of the code base by the entire team.

**Comment by JEstes93** [comment]
Met with team, folder portion of back-end is behind expectations. Team agrees on the value of this but currently placing it low priority.

**Comment by forestwhill** [comment]
All current folder pieces have java docs. Will update as needed until items are closed.

**Comment by JEstes93** [comment]
I put this back into New Issues for fresh consideration at the top of the next sprint. I feel a quick double-check to ensure a tidy, thorough codebase at the beginning of the next sprint will dramatically increase speed and efficiency during development, especially pending any further team scrambles.

**Comment by JEstes93** [comment]
This is a continuous on-going process, that doesn't need a specific issue.
