### ISSUE TITLE
Determine Dto Structures

### ISSUE THREAD

**Issue by wmarttala** [cooksystemsinc/final-project-orange#6]
We need to determine what our dtos will look like for each endpoint.

**Comment by JEstes93** [comment]
This is in flex pending Folder-related API interactions.

**Comment by forestwhill** [comment]
Current Folder DTO structure is as follows:

There are two folder DTOs, one containing all DTOs for files and folders located within the selected folder, and one for viewing the structure of the folder without the file data.

FolderViewDTO:
`
{
  "uid": Long,
  "name": String,
  "created": Date,
  "lastModified": Date,
  "containerId": Long,
  "inTrash": boolean
}
`

FolderDTO:
`
{
  "uid": Long,
  "name": String,
  "created": Date,
  "lastModified": Date,
  "filesContained": List<FileDTO>,
  "foldersContained": List<FolderDTO>,
  "containerId": Long,
  "inTrash": boolean
}
`

**Comment by JEstes93** [comment]
### Current File/Folder JSON response structures in JSDocs
```
/**
 * @typedef FileResponse
 * @property {Number} uid File's unique ID
 * @property {String} name File's name
 * @property {Number} [containerId] File's containing folder, file contained in root if null or undefined
 * @property {Boolean} inTrash Whether or not file is currently in the trash bin/staged for permanent deletion
 */

/**
 * @typedef FolderResponse
 * @property {Number} uid Folder's unique ID
 * @property {String} name Folder's name
 * @property {FileResponse[]} filesContained Files this folder directly contains
 * @property {FolderResponse[]} foldersContained Folders this folder directly contains
 * @property {Number} [containerId] Folder's containing folder, folder contained in root if null or undefined
 * @property {Boolean} inTrash Whether or not file is currently in the trash bin/staged for permanent deletion
 */
```
