### ISSUE TITLE
make the trash icon functional

### ISSUE THREAD

**Issue by oldmanriver2235** [cooksystemsinc/final-project-orange#61]
write an onClick function that takes the selected component to the trash bin

**Comment by wmarttala** [comment]
Probably more accurate that onClick should dispatch some Redux action. In this case it will probably be an asynchronous action which will have the server toggle the trash boolean and on success that asynchronous action will dispatch a synchronous one to update the UI.

**Comment by wmarttala** [comment]
This seems inherently tied to the issues creating ducks.

**Comment by JEstes93** [comment]
Worked with Austin on this, functions to spec
