### ISSUE TITLE
Handle File & Folder Upload with Dropzone

### ISSUE THREAD

**Issue by forestwhill** [cooksystemsinc/final-project-orange#64]
Dropzone seems to be the simplest way to get data for all files in a folder.

https://react-dropzone.netlify.com/

**Comment by JEstes93** [comment]
Discussing this with Forest

**Comment by forestwhill** [comment]
This works for files and can see folders, but upload functionality has not yet been implemented for folders. Separating this into a new issue so I can close the upload file issue.
